const style = {
	/* 对应@/common/xg.scss文件样式 */
	
	//文字尺寸
	UNI_FONT_SIZE_MI: '10px',
	UNI_FONT_SIZE_HG: '18px',
	UNI_FONT_SIZE_MX: '20px',
	
	//文字颜色
	UNI_TEXT_COLOR_RED: '#ed1c24',
	
	//图标尺寸
	UNI_ICON_SIZE_MI: '20px',
	UNI_ICON_SIZE_SM: '30px',
	UNI_ICON_SIZE_BASE: '40px',
	UNI_ICON_SIZE_LG: '50px',
	UNI_ICON_SIZE_HG: '60px',
	UNI_ICON_SIZE_MX: '70px',
	
	//图标颜色
	UNI_ICON_COLOR_BASE: '#333',
	UNI_ICON_COLOR_WHITE: '#FFF',
	UNI_ICON_COLOR_TITLE: '#333',
	UNI_ICON_COLOR_SUBTITLE: '#999',
	
	
	
	/* 对应@/uni.scss文件样式 */
	
	//行为相关颜色
	UNI_COLOR_PRIMARY: '#007AFF',
	UNI_COLOR_SUCCESS: '#4cd964',
	UNI_COLOR_WARNING: '#f0ad4e',
	UNI_COLOR_ERROR: '#dd524d',
	
	//文字基本颜色
	UNI_TEXT_COLOR: '#333',
	UNI_TEXT_COLOR_INVERSE: '#FFF',
	UNI_TEXT_COLOR_GREY: '#999',
	UNI_TEXT_COLOR_PLACEHOLDER: '#808080',
	UNI_TEXT_COLOR_DISABLE: '#C0C0C0',
	
	//背景颜色
	UNI_BG_COLOR: '#FFF',
	UNI_BG_COLOR_GREY: '#f8f8f8',
	UNI_BG_COLOR_HOVER: '#F1F1F1',
	UNI_BG_COLOR_MASK: 'rgba(0, 0, 0, 0.4)',
	
	//边框颜色
	UNI_BORDER_COLOR: '#c8c7cc',
	
	// /* 尺寸变量 */
	
	//文字尺寸 
	UNI_FONT_SIZE_SM: '12px',
	UNI_FONT_SIZE_BASE: '14px',
	UNI_FONT_SIZE_LG: '16px',
	
	//图片尺寸 
	UNI_IMG_SIZE_SM: '40rpx',
	UNI_IMG_SIZE_BASE: '52rpx',
	UNI_IMG_SIZE_LG: '80rpx',
	
	// Border Radius 
	UNI_BORDER_RADIUS_SM: '4rpx',
	UNI_BORDER_RADIUS_BASE: '6rpx',
	UNI_BORDER_RADIUS_LG: '12rpx',
	UNI_BORDER_RADIUS_CIRCLE: '50%',
	
	// 水平间距 
	UNI_SPACING_ROW_SM: '12rpx',
	UNI_SPACING_ROW_BASE: '24rpx',
	UNI_SPACING_ROW_LG: '36rpx',
	
	// 垂直间距
	UNI_SPACING_COL_SM: '10rpx',
	UNI_SPACING_COL_BASE: '20rpx',
	UNI_SPACING_COL_LG: '30rpx',
	
	//透明度 
	UNI_OPACITY_DISABLED: 0.3,
	
	//文章场景相关
	UNI_COLOR_TITLE: '#2C405A',
	UNI_FONT_SIZE_TITLE: '40rpx',
	UNI_COLOR_SUBTITLE: '#555555',
	UNI_FONT_SIZE_SUBTITLE: '36rpx',
	UNI_COLOR_PARAGRAPH: '#3F536E',
	UNI_FONT_SIZE_PARAGRAPH: '30rpx',
	
}

export default style;