const style = {
	/* 对应@/common/xg.scss文件样式 */
	
	//文字颜色
	UNI_TEXT_COLOR_RED: '#ed1c24',
	UNI_TEXT_COLOR_WHITE: '#FFFFFF',
	
	//图标尺寸
	UNI_ICON_SIZE_MI: '20rpx',
	UNI_ICON_SIZE_SM: '40rpx',
	UNI_ICON_SIZE_MD: '50rpx',
	UNI_ICON_SIZE_BASE: '80rpx',
	UNI_ICON_SIZE_LG: '120rpx',
	UNI_ICON_SIZE_HG: '160rpx',
	UNI_ICON_SIZE_MX: '200rpx',
	
	
	/* 对应@/uni.scss文件样式 */
	
	//行为相关颜色
	UNI_COLOR_PRIMARY: '#007AFF',
	UNI_COLOR_SUCCESS: '#4cd964',
	UNI_COLOR_WARNING: '#f0ad4e',
	UNI_COLOR_ERROR: '#dd524d',
	
	//文字基本颜色
	UNI_TEXT_COLOR: '#333',
	UNI_TEXT_COLOR_INVERSE: '#FFF',
	UNI_TEXT_COLOR_GREY: '#999',
	UNI_TEXT_COLOR_PLACEHOLDER: '#808080',
	UNI_TEXT_COLOR_DISABLE: '#C0C0C0',
	
	//背景颜色
	UNI_BG_COLOR: '#FFF',
	UNI_BG_COLOR_GREY: '#f8f8f8',
	UNI_BG_COLOR_HOVER: '#F1F1F1',
	UNI_BG_COLOR_MASK: 'rgba(0, 0, 0, 0.4)',
	UNI_BG_COLOR_MASK_WHITE: 'rgba(255, 255, 255, 0.4)',
	UNI_BG_COLOR_PINK: 'pink',
	UNI_BG_COLOR_RED: 'red',
	UNI_BG_COLOR_YELLOW: 'yellow',
	UNI_BG_COLOR_ORANGE: 'orange',
	UNI_BG_COLOR_BLUE: 'blue',
	UNI_BG_COLOR_BLACK: 'black',
	
	//边框颜色
	UNI_BORDER_COLOR: '#c8c7cc',
	
	// /* 尺寸变量 */
	
	//文字尺寸 
	UNI_FONT_SIZE_MARO: '20rpx',
	UNI_FONT_SIZE_MI: '24rpx',
	UNI_FONT_SIZE_SM: '28rpx',
	UNI_FONT_SIZE_BASE: '32rpx',
	UNI_FONT_SIZE_LG: '36rpx',
	UNI_FONT_SIZE_HG: '40rpx',
	UNI_FONT_SIZE_MX: '44rpx',
	
	//图片尺寸 
	UNI_IMG_SIZE_SM: '40rpx',
	UNI_IMG_SIZE_BASE: '52rpx',
	UNI_IMG_SIZE_LG: '80rpx',
	
	// Border Radius 
	UNI_BORDER_RADIUS_MI: '4rpx',
	UNI_BORDER_RADIUS_SM: '10rpx',
	UNI_BORDER_RADIUS_BASE: '20rpx',
	UNI_BORDER_RADIUS_LG: '30rpx',
	UNI_BORDER_RADIUS_HG: '40rpx',
	UNI_BORDER_RADIUS_CIRCLE: '50%',
	
	// 水平间距 
	UNI_SPACING_ROW_MI: '8rpx',
	UNI_SPACING_ROW_SM: '12rpx',
	UNI_SPACING_ROW_BASE: '24rpx',
	UNI_SPACING_ROW_LG: '36rpx',
	UNI_SPACING_ROW_HG: '48rpx',
	UNI_SPACING_ROW_MX: '60rpx',
	
	// 垂直间距
	UNI_SPACING_COL_MI: '6rpx',
	UNI_SPACING_COL_SM: '10rpx',
	UNI_SPACING_COL_BASE: '20rpx',
	UNI_SPACING_COL_LG: '30rpx',
	UNI_SPACING_COL_HG: '40rpx',
	UNI_SPACING_COL_MX: '50rpx',
	
	//透明度 
	UNI_OPACITY_DISABLED: 0.3,
	
	//文章场景相关
	UNI_COLOR_TITLE: '#2C405A',
	UNI_FONT_SIZE_TITLE: '40rpx',
	UNI_COLOR_SUBTITLE: '#555555',
	UNI_FONT_SIZE_SUBTITLE: '36rpx',
	UNI_COLOR_PARAGRAPH: '#3F536E',
	UNI_FONT_SIZE_PARAGRAPH: '30rpx',
	
}

export default style;