const style = {
	/* 对应@/common/xg.scss文件样式 */
	//颜色
	UNI_COLOR_WHITE: '#FFFFFF',
	UNI_COLOR_RED: '#dd524d',
	UNI_COLOR_PINK: 'pink',
	UNI_COLOR_GREEN: '#06A688',
	UNI_COLOR_BLUE: 'blue',
	UNI_COLOR_ORANGE: 'orange',
	UNI_COLOR_GREY: '#E5E5E5',
	UNI_COLOR_GREYBLACK: '#777',
	UNI_COLOR_BLACK: '#000',
	
	//字体大小
	UNI_FONT_SIZE_XS: '20rpx',
	UNI_FONT_SIZE_XL: '36rpx',
	
	// 图片尺寸
	UNI_IMG_SIZE_XS: '30rpx',
	UNI_IMG_SIZE_XL: '110rpx',
	
	
	
	/* 对应@/uni.scss文件样式 */
	
	//行为相关颜色
	UNI_COLOR_PRIMARY: '#007AFF',
	UNI_COLOR_SUCCESS: '#4cd964',
	UNI_COLOR_WARNING: '#f0ad4e',
	UNI_COLOR_ERROR: '#dd524d',
	
	//文字基本颜色
	UNI_TEXT_COLOR: '#333',
	UNI_TEXT_COLOR_INVERSE: '#FFF',
	UNI_TEXT_COLOR_GREY: '#999',
	UNI_TEXT_COLOR_PLACEHOLDER: '#808080',
	UNI_TEXT_COLOR_DISABLE: '#C0C0C0',
	
	
	//背景颜色
	UNI_BG_COLOR: '#FFF',
	UNI_BG_COLOR_GREY: '#f8f8f8',
	UNI_BG_COLOR_BLACKGREY: '#CCC',
	UNI_BG_COLOR_HOVER: '#F1F1F1',
	UNI_BG_COLOR_MASK: 'rgba(0, 0, 0, 0.4)',
	
	
	//边框颜色
	UNI_BORDER_COLOR: '#c8c7cc',
	
	
	// /* 尺寸变量 */
	
	//文字尺寸 
	UNI_FONT_SIZE_SM: '24rpx',
	UNI_FONT_SIZE_BASE: '28rpx',
	UNI_FONT_SIZE_LG: '32rpx',
	
	
	//图片尺寸 
	UNI_IMG_SIZE_SM: '40rpx',
	UNI_IMG_SIZE_BASE: '52rpx',
	UNI_IMG_SIZE_LG: '80rpx',
	
	// Border Radius 
	UNI_BORDER_RADIUS_XS: '2rpx',
	UNI_BORDER_RADIUS_SM: '4rpx',
	UNI_BORDER_RADIUS_BASE: '6rpx',
	UNI_BORDER_RADIUS_LG: '12rpx',
	UNI_BORDER_RADIUS_XL: '24rpx',
	UNI_BORDER_RADIUS_RECT_CIRCLE: '10000px',
	UNI_BORDER_RADIUS_CIRCLE: '50%',
	
	// 水平间距 
	UNI_SPACING_ROW_XS: '5rpx',
	UNI_SPACING_ROW_SM: '10rpx',
	UNI_SPACING_ROW_BASE: '20rpx',
	UNI_SPACING_ROW_LG: '30rpx',
	UNI_SPACING_ROW_XL: '40rpx',
	
	// 垂直间距
	UNI_SPACING_COL_XS: '4rpx',
	UNI_SPACING_COL_SM: '8rpx',
	UNI_SPACING_COL_BASE: '16rpx',
	UNI_SPACING_COL_LG: '24rpx',
	UNI_SPACING_COL_XL: '32rpx',
	
	//透明度 
	UNI_OPACITY_DISABLED: 0.3,
	
	//文章场景相关
	UNI_COLOR_TITLE: '#2C405A',
	UNI_FONT_SIZE_TITLE: '40rpx',
	UNI_COLOR_SUBTITLE: '#555555',
	UNI_FONT_SIZE_SUBTITLE: '36rpx',
	UNI_COLOR_PARAGRAPH: '#3F536E',
	UNI_FONT_SIZE_PARAGRAPH: '30rpx',
	
}

export default style;